name: Format Code

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort
        
    - name: Format with black
      run: |
        black --check --diff .
        
    - name: Format with isort
      run: |
        isort --check-only --diff .
        
    - name: Auto-format with black
      if: github.event_name == 'workflow_dispatch'
      run: |
        black .
        
    - name: Auto-format with isort
      if: github.event_name == 'workflow_dispatch'
      run: |
        isort .
        
    - name: Commit and push changes
      if: github.event_name == 'workflow_dispatch'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --quiet && git diff --staged --quiet || git commit -m "Auto-format code with black and isort"
        git push 